backend:
  name: github
  repo: Aecaichang/aecaichang
  branch: main
  base_url: https://aecaichang.vercel.app
  auth_endpoint: api/auth

media_folder: "src/assets/blog"
public_folder: "@assets/blog"

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Image", name: "heroImage", widget: "image", required: false }
      - { label: "Image Alt", name: "heroImageAlt", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
